apiVersion: apps/v1
kind: Deployment
metadata:
  name: flux-demo
  labels:
    app: flux-demo
spec:
  replicas: 2
  selector:
    matchLabels:
      app: flux-demo
  template:
    metadata:
      labels:
        app: flux-demo
    spec:
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
            - matchExpressions:
              - key: node-role.kubernetes.io/master
                operator: NotIn
                values:
                - "true"
      containers:
      - name: flux-demo
        image: lekaf974/flux-demo:v3
        resources:
          limits:
            memory: "128Mi"
            cpu: "500m"
        ports:
        - containerPort: 8080
        env:
        # Define the environment variable
        - name: ENVIRONMENT
          valueFrom:
            configMapKeyRef:
              name: flux-demo-cm
              key: ENVIRONMENT
